global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'poi-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['poi-service:8082']
      
  - job_name: 'bookings-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bookings-service:8083']
